services:
  spring-boot:
    container_name: 'guide-spring-boot'
    image: 'guide-spring-boot:latest'
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - spring-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
networks:
    spring-network:
        driver: bridge